version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/deploy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: deploy

archives:
  - format: binary
    strip_binary_directory: true
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
  draft: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"
      - "^revert:"
      - "^style:"
      - "^refactor:"
      - "^perf:"
