version: '3'

vars:
  TEST_FLAGS: -race -failfast -v

tasks:
  check:
    desc: Run fmt and code quality checks
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  check:fmt:
    desc: Format all Go files
    cmds:
      - go fmt ./...

  check:vet:
    desc: Run go vet on all packages
    cmds:
      - go vet ./...

  check:lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  check:test:
    desc: Run tests
    cmds:
      - go test {{.TEST_FLAGS}} ./...

  release:test:
    desc: Test the release
    cmds:
      - goreleaser release --snapshot --clean

  release:version:
    desc: Show current version
    cmds:
      - svu current

  release:patch:
    desc: Bump patch version
    cmds:
      - svu patch

  release:minor:
    desc: Bump minor version
    cmds:
      - svu minor

  release:major:
    desc: Bump major version
    cmds:
      - svu major
